---
- name: Install and configure Grafana on Ubuntu 24
  hosts: all
  become: yes
  vars:
    grafana_version: "9.6.3"  # Specify the Grafana version you want to install
    grafana_repo_url: "https://packages.grafana.com/oss/deb"  # URL for the Grafana package

  tasks:
    - name: Update apt cache and install dependencies
      apt:
        name:
          - software-properties-common
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb {{ grafana_repo_url }} stable main"
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana package
      apt:
        name: grafana={{ grafana_version }}
        state: present

    - name: Ensure Grafana service is started and enabled
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Abrir puerto para Grafana en el firewall
      ufw:
        rule: allow
        port: 3000/tcp
        proto: tcp
        src: any

    - name: Ensure Grafana service is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configure Grafana data sources (optional)
      template:
        src: grafana_datasource.yml.j2
        dest: /etc/grafana/provisioning/datasources/datasource.yml
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Grafana

  handlers:
    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
