---
- name: Instalar y configurar Grafana
  hosts: all
  become: yes

  tasks:
    - name: Añadir la clave GPG de Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Añadir el repositorio de Grafana
      apt_repository:
        repo: deb https://apt.grafana.com stable main
        state: present

    - name: Actualizar la caché de APT
      apt:
        update_cache: yes

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Iniciar y habilitar Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Abrir puerto para Grafana en el firewall
      ufw:
        rule: allow
        port: 3000/tcp
        proto: tcp
        src: any
