---
- name: Update Zabbix repo and Agent2
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    # Get distrib version for good repo
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts

    # Ubuntu 22
    - name: Install last deb for update repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb
        allow_downgrade: yes
      when: 
        - ansible_facts['distribution_major_version'] == "22"

    # Check if Zabbix is present
    - name: Check if Zabbix is present
      stat: 
        path: /etc/zabbix/zabbix_agent2.conf
      register: zabbix_config_file

    # Write message if Zabbix is presnet
    - name: Zabbix agent is present
      debug: 
        msg: "Zabbix Agent is installed !"
      when: zabbix_config_file.stat.exists

    # Update Repo and new zabbix agent
    - name: Update Zabbix agent
      ansible.builtin.apt:
        name: zabbix-agent2
        update_cache: yes



#ansible-playbook /etc/ansible/linux/pb-ubuntu-update-zabbix.yml -i /etc/ansible/hosts_ubuntu.yml -f 1 -v
